### ISSUE TITLE
Instructions to run on replit

### ISSUE THREAD

**Issue by NEWTONASOP** [saalikmubeen/talkhouse#1]
hello i like your project i am trying to run it on replit can you give me instructions please?

**Comment by saalikmubeen** [comment]
It's not intended and ideal to run on replit. I'll suggest try running on your local machine

**Comment by NEWTONASOP** [comment]
> It's not intended and ideal to run on replit. I'll suggest try running on your local machine

where i can host it then?

**Comment by saalikmubeen** [comment]
> > It's not intended and ideal to run on replit. I'll suggest try running on your local machine
> 
> where i can host it then?

Try running it on your local machine, pc or Mac. Readme contains detailed instructions on how to get talkhouse up and running locally. Just try a little, you can make it work 😅

**Comment by NEWTONASOP** [comment]
> > > It's not intended and ideal to run on replit. I'll suggest try running on your local machine
> > 
> > 
> > where i can host it then?
> 
> Try running it on your local machine, pc or Mac. Readme contains detailed instructions on how to get talkhouse up and running locally. Just try a little, you can make it work 😄

i can but can i host it somwhere else?

**Comment by saalikmubeen** [comment]
> > > > It's not intended and ideal to run on replit. I'll suggest try running on your local machine
> > > 
> > > 
> > > where i can host it then?
> > 
> > 
> > Try running it on your local machine, pc or Mac. Readme contains detailed instructions on how to get talkhouse up and running locally. Just try a little, you can make it work 😄
> 
> i can bu

**Comment by saalikmubeen** [comment]
> > > > It's not intended and ideal to run on replit. I'll suggest try running on your local machine
> > > 
> > > 
> > > where i can host it then?
> > 
> > 
> > Try running it on your local machine, pc or Mac. Readme contains detailed instructions on how to get talkhouse up and running locally. Just try a little, you can make it work 😄
> 
> i can but can i host it somwhere else?

You can host frontend on netlify and server on the heroku for free and the mongodb database can be hosted on mongo atlas. To put all these pieces together will require some prior knowledge of deployments and some knowledge of hosting servers .

**Comment by NEWTONASOP** [comment]
> > > > > It's not intended and ideal to run on replit. I'll suggest try running on your local machine
> > > > 
> > > > 
> > > > where i can host it then?
> > > 
> > > 
> > > Try running it on your local machine, pc or Mac. Readme contains detailed instructions on how to get talkhouse up and running locally. Just try a little, you can make it work 😄
> > 
> > 
> > i can but can i host it somwhere else?
> 
> You can host frontend on netlify and server on the heroku for free and the mongodb database can be hosted on mongo atlas. To put all these pieces together will require some prior knowledge of deployments and some knowledge of hosting servers .

csn you make a readme for it PLS
